### ISSUE TITLE
Randomized algorithms roadmap

### ISSUE THREAD

**Issue by jiahao** [JuliaMath/IterativeSolvers.jl#33]
This issue tracks the implementation of randomized algorithms that have appeared in the literature.

Dixon, 1983 [doi:10.1137/0720053](http://epubs.siam.org/doi/abs/10.1137/0720053):
- [x] Randomized condition number estimate (implemented as `rcond`)
- [x] Randomized extremal eigenvalue estimates (implemented as `reigmax` and `reigmin`)

Cheng, Gimbutas, Martinsson and Rokhlin, 2005 [doi:10.1137/030602678](http://epubs.siam.org/doi/abs/10.1137/030602678)
- [ ] Interpolative decomposition (the four-term variant)

Liberty, Woolfe, Martinsson, Rokhlin, Tygert, 2007 [doi:10.1073/pnas.0709640104](http://www.pnas.org/content/104/51/20167)
- [x] Randomized norm estimate (implemented as `rnorms`)
- [x] Interpolative decomposition (the two-term variant; currently a very hacky version is implemented in `idfact`)

Strohmer and Vershynin, 2009 [doi:10.1007/s00041-008-9030-4](http://link.springer.com/article/10.1007%2Fs00041-008-9030-4): 
- [ ] randomized Kaczmarz algorithm

Halko, Martinsson and Tropp 2011 [doi:10.1137/090771806](http://epubs.siam.org/doi/abs/10.1137/090771806)
- [x] Lemma 4.1: Randomized norm estimate (implemented as `rnorm`)
- [x] Algorithm 4.1: randomized range finder (implemented as `rrange`)
- [x] Algorithm 4.2: adaptive randomized range finer (implemented as `rrange_adaptive`)
- [x] Algorithm 4.4: randomized subspace iteration (implemented as `rrange_si`)
- [x] Algorithm 4.5: fast randomized range finder (implemented as `rrange_f`)
- [ ] Variant of Algorithm 4.5 using randomized Givens rotations
- [x] Algorithm 5.1: direct SVD (implemented as `svdfact_restricted`)
- [x] Algorithm 5.2: SVD via row extraction (implemented as `svdfact_re`) 
- [x] Algorithm 5.3: direct eigenvalue decomposition (implemented as `eigfact_restricted`)
- [x] Algorithm 5.4: eigenvalue decomposition via row extraction (implemented as `eigfact_re`) 
- [x] Algorithm 5.5: eigenvalue decomposition via Nyström method (implemented as `eigfact_nystrom`) 
- [x] Algorithm 5.6: eigenvalue decomposition in one pass for Hermitian matrices (implemented as `eigfact_onepass`) 
- [x] Algorithm 5.6: eigenvalue decomposition in one pass for non-Hermitian matrices (currently implemented in a hacky way in `eigfact_onepass`)

Meng, Saunders and Mahoney, 2014 [doi:10.1137/120866580](http://epubs.siam.org/doi/abs/10.1137/120866580)
- [ ] LSRN - least squares solver based on randomized normal projections

**Comment by haampie** [comment]
Closed because of #179
